/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.my.teleport.system.kafka.agent.avro.model;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class AgentCreatedAvroModel extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -6662490801376055907L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AgentCreatedAvroModel\",\"namespace\":\"com.my.teleport.system.kafka.agent.avro.model\",\"fields\":[{\"name\":\"id\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"agentId\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"name\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<AgentCreatedAvroModel> ENCODER =
      new BinaryMessageEncoder<AgentCreatedAvroModel>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<AgentCreatedAvroModel> DECODER =
      new BinaryMessageDecoder<AgentCreatedAvroModel>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<AgentCreatedAvroModel> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<AgentCreatedAvroModel> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<AgentCreatedAvroModel> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<AgentCreatedAvroModel>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this AgentCreatedAvroModel to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a AgentCreatedAvroModel from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a AgentCreatedAvroModel instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static AgentCreatedAvroModel fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.String id;
  private java.lang.String agentId;
  private java.lang.String name;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AgentCreatedAvroModel() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param agentId The new value for agentId
   * @param name The new value for name
   */
  public AgentCreatedAvroModel(java.lang.String id, java.lang.String agentId, java.lang.String name) {
    this.id = id;
    this.agentId = agentId;
    this.name = name;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return agentId;
    case 2: return name;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      null,
      null,
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = value$ != null ? value$.toString() : null; break;
    case 1: agentId = value$ != null ? value$.toString() : null; break;
    case 2: name = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.String getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.String value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'agentId' field.
   * @return The value of the 'agentId' field.
   */
  public java.lang.String getAgentId() {
    return agentId;
  }


  /**
   * Sets the value of the 'agentId' field.
   * @param value the value to set.
   */
  public void setAgentId(java.lang.String value) {
    this.agentId = value;
  }

  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public java.lang.String getName() {
    return name;
  }


  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.String value) {
    this.name = value;
  }

  /**
   * Creates a new AgentCreatedAvroModel RecordBuilder.
   * @return A new AgentCreatedAvroModel RecordBuilder
   */
  public static com.my.teleport.system.kafka.agent.avro.model.AgentCreatedAvroModel.Builder newBuilder() {
    return new com.my.teleport.system.kafka.agent.avro.model.AgentCreatedAvroModel.Builder();
  }

  /**
   * Creates a new AgentCreatedAvroModel RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AgentCreatedAvroModel RecordBuilder
   */
  public static com.my.teleport.system.kafka.agent.avro.model.AgentCreatedAvroModel.Builder newBuilder(com.my.teleport.system.kafka.agent.avro.model.AgentCreatedAvroModel.Builder other) {
    if (other == null) {
      return new com.my.teleport.system.kafka.agent.avro.model.AgentCreatedAvroModel.Builder();
    } else {
      return new com.my.teleport.system.kafka.agent.avro.model.AgentCreatedAvroModel.Builder(other);
    }
  }

  /**
   * Creates a new AgentCreatedAvroModel RecordBuilder by copying an existing AgentCreatedAvroModel instance.
   * @param other The existing instance to copy.
   * @return A new AgentCreatedAvroModel RecordBuilder
   */
  public static com.my.teleport.system.kafka.agent.avro.model.AgentCreatedAvroModel.Builder newBuilder(com.my.teleport.system.kafka.agent.avro.model.AgentCreatedAvroModel other) {
    if (other == null) {
      return new com.my.teleport.system.kafka.agent.avro.model.AgentCreatedAvroModel.Builder();
    } else {
      return new com.my.teleport.system.kafka.agent.avro.model.AgentCreatedAvroModel.Builder(other);
    }
  }

  /**
   * RecordBuilder for AgentCreatedAvroModel instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AgentCreatedAvroModel>
    implements org.apache.avro.data.RecordBuilder<AgentCreatedAvroModel> {

    private java.lang.String id;
    private java.lang.String agentId;
    private java.lang.String name;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.my.teleport.system.kafka.agent.avro.model.AgentCreatedAvroModel.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.agentId)) {
        this.agentId = data().deepCopy(fields()[1].schema(), other.agentId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.name)) {
        this.name = data().deepCopy(fields()[2].schema(), other.name);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing AgentCreatedAvroModel instance
     * @param other The existing instance to copy.
     */
    private Builder(com.my.teleport.system.kafka.agent.avro.model.AgentCreatedAvroModel other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.agentId)) {
        this.agentId = data().deepCopy(fields()[1].schema(), other.agentId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.name)) {
        this.name = data().deepCopy(fields()[2].schema(), other.name);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.String getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.my.teleport.system.kafka.agent.avro.model.AgentCreatedAvroModel.Builder setId(java.lang.String value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.my.teleport.system.kafka.agent.avro.model.AgentCreatedAvroModel.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'agentId' field.
      * @return The value.
      */
    public java.lang.String getAgentId() {
      return agentId;
    }


    /**
      * Sets the value of the 'agentId' field.
      * @param value The value of 'agentId'.
      * @return This builder.
      */
    public com.my.teleport.system.kafka.agent.avro.model.AgentCreatedAvroModel.Builder setAgentId(java.lang.String value) {
      validate(fields()[1], value);
      this.agentId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'agentId' field has been set.
      * @return True if the 'agentId' field has been set, false otherwise.
      */
    public boolean hasAgentId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'agentId' field.
      * @return This builder.
      */
    public com.my.teleport.system.kafka.agent.avro.model.AgentCreatedAvroModel.Builder clearAgentId() {
      agentId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public java.lang.String getName() {
      return name;
    }


    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public com.my.teleport.system.kafka.agent.avro.model.AgentCreatedAvroModel.Builder setName(java.lang.String value) {
      validate(fields()[2], value);
      this.name = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public com.my.teleport.system.kafka.agent.avro.model.AgentCreatedAvroModel.Builder clearName() {
      name = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public AgentCreatedAvroModel build() {
      try {
        AgentCreatedAvroModel record = new AgentCreatedAvroModel();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.String) defaultValue(fields()[0]);
        record.agentId = fieldSetFlags()[1] ? this.agentId : (java.lang.String) defaultValue(fields()[1]);
        record.name = fieldSetFlags()[2] ? this.name : (java.lang.String) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<AgentCreatedAvroModel>
    WRITER$ = (org.apache.avro.io.DatumWriter<AgentCreatedAvroModel>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<AgentCreatedAvroModel>
    READER$ = (org.apache.avro.io.DatumReader<AgentCreatedAvroModel>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










