version: '3.7'
services:
  init-kafka:
    image: confluentinc/cp-kafka:${KAFKA_VERSION}
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      # block until kafka is reachable
      kafka-topics --bootstrap-server kafka-broker-1:19092 --list
      
      echo -e 'Deleting kafka topics'
      kafka-topics --bootstrap-server kafka-broker-1:19092 --topic agent-created --delete --if-exists
      kafka-topics --bootstrap-server kafka-broker-1:19092 --topic client-created --delete --if-exists
      kafka-topics --bootstrap-server kafka-broker-1:19092 --topic order-processed --delete --if-exists


      echo -e 'Creating kafka topics'
      kafka-topics --bootstrap-server kafka-broker-1:19092 --create --if-not-exists --topic agent-created --replication-factor 3 --partitions 3
      kafka-topics --bootstrap-server kafka-broker-1:19092 --create --if-not-exists --topic client-created --replication-factor 3 --partitions 3
      kafka-topics --bootstrap-server kafka-broker-1:19092 --create --if-not-exists --topic order-processed --replication-factor 3 --partitions 3


      echo -e 'Successfully created the following topics:'
      kafka-topics --bootstrap-server kafka-broker-1:19092 --list
      "
    networks:
      - ${GLOBAL_NETWORK:-kafka}